import { Geist, Geist_Mono } from "next/font/google";
import { ResponseProvider } from "./context/ResponseContext";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Chronos",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
     <html lang="en">
      <body>
        <ResponseProvider>
          {children}
        </ResponseProvider>
      </body>
    </html>
  );
}
